### ISSUE TITLE
easyenergy configuration example

### ISSUE THREAD

**Issue by Timple** [kvanhoorn/hass#1]
So this is the main google hit for "home-assistant easyenergy". Awesome that someone started already on it 😎.

However I get 

```
Invalid config
The following integrations and platforms could not be set up:

easyenergy
```

Would you mind sharing an example entry for `configuration.yaml`?

(Using home-assistant core-2021.10.3)

**Comment by kvanhoorn** [comment]
My config looks like this:

`
sensor:
- platform: easyenergy
- platform: easyenergy
  timedelta: 1
`
