### ISSUE TITLE
Current price instead of average

### ISSUE THREAD

**Issue by Timple** [kvanhoorn/hass#4]
For the new energy dashboard, the entity needs to be the current price, not an average.

Would you accept a PR that modifies this?
The attributes can stay the same, so automations based on future costs may still function.

**Comment by kvanhoorn** [comment]
Hi Timple,

Sure, the main goal was to determine the cheapest price of the day to alert me about the financially best hour to use energy the next day.
Still WIP currently, not expecting it to drop below zero soon.

**Comment by Timple** [comment]
I switched energy supplier...

Thanks for your implementation thusfar!

**Comment by kvanhoorn** [comment]
Hi Tim,

Not the right moment to switch I believe, prices are already dropping after 2 expensive months.
Thanks for helping me out!

**Comment by Timple** [comment]
Well, the prices where getting so expensive that I could take the gamble.
If they turn cheaper in two months, I pay the 250,- fine and still didn't loose anything.
